[package]
name = "taupipp"
version = "0.1.0"
authors = ["nalos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filecoin = { git="https://github.com/filecoin-project/powersoftau",package="powersoftau"}
zcash = { git="https://github.com/ebfull/powersoftau",package="powersoftau"}
#zcash = { path="../zcashptau", package="powersoftau"}
